blank_issues_enabled: false
contact_links:
  - name: "#phoenix616 IRC channel on irc.esper.net"
    url: "https://kiwiirc.com/client/irc.esper.net/#phoenix616"
    about: Phoenix616's public IRC channel to discuss any of his projects
  - name: "Phoenix616's Discord"
    url: "https://phoenix616.dev/discord"
    about: The discord server for all of Phoenix616's stuff. Bridged to IRC.
  - name: SpigotMC PM
    url: https://www.spigotmc.org/conversations/add?to=Phoenix616&title=Question
    about: Ask Phoenix616 questions privately
  - name: Minebench.de Discord
    url: https://minebench.de/discord
    about: If you can speak German then feel free to join the Minebench.de Discord!
